### ISSUE TITLE
I need some guidance

### ISSUE THREAD

**Issue by Yexiansen66** [Professor-Paradox/LearningProgramming#1]
I want to learn some javaScript project,what should I do?

**Comment by Professor-Paradox** [comment]
Do you have any programming knowledge?
If so start learning from w3schools,youtube.

Currently iam preparing my guide on java later i will prepare for python.

javascript guide will take some time to prepare.
hope you understand.
But this guide with concepts is same for all languages the syntax may differ.

**Comment by Professor-Paradox** [comment]
You Still Have any doubts?
